# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/ClockModule/ClockModule.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ClockModule || ORIG_REF_NAME==ClockModule} -quiet] -quiet

# IP: bd/ClockModule/ip/ClockModule_clk_wiz_0_0/ClockModule_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ClockModule_clk_wiz_0_0 || ORIG_REF_NAME==ClockModule_clk_wiz_0_0} -quiet] -quiet

# XDC: d:/Estudio/Lenguajes-descriptivos-de-hardware/repo/verilog/VGA-Module/VGA-Module.gen/sources_1/bd/ClockModule/ClockModule_ooc.xdc
